id: admin-analytics-green-controller
kind: ReplicationController
apiVersion: v1beta1
labels: 
  name: admin-analytics-green
  version: 1.0.0
desiredState: 
  replicas: 2
  replicaSelector:
    name: admin-analytics-green
    version: 1.0.0
  podTemplate:
    labels:
      name: admin-analytics-green
      app: admin-analytics-green
      version: 1.0.0
    desiredState: 
      manifest: 
        version: v1beta1
        id: admin-analytics-green
        containers: 
          - name: admin-analytics-green
            image: octoblu/admin-analytics
            ports: 
              - containerPort: 8888

