id: octoblu-oauth-provider-controller-1.0.0
kind: ReplicationController
apiVersion: v1beta1
labels:
  name: octoblu-oauth-provider
  version: 1.0.0
desiredState:
  replicas: 2
  replicaSelector:
    name: octoblu-oauth-provider
    version: 1.0.0
  podTemplate:
    labels:
      name: octoblu-oauth-provider
      app: octoblu-oauth-provider
      version: 1.0.0
    desiredState:
      manifest:
        version: v1beta1
        id: octoblu-oauth-provider
        containers:
          - name: octoblu-oauth-provider
            image: octoblu/octoblu-oauth-provider
            ports:
              - containerPort: 9000

